import { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'en' | 'bn';

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const STORAGE_KEY = 'cylinder-express-language';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'language.label': 'Language',
    'language.english': 'English',
    'language.bangla': 'বাংলা',
    'language.switchToBangla': 'বাংলা',
    'language.switchToEnglish': 'English',
    'nav.home': 'Home',
    'nav.offers': 'Offers',
    'nav.products': 'Products',
    'nav.cart': 'Cart',
    'nav.orders': 'Orders',
    'nav.addresses': 'Addresses',
    'nav.admin': 'Administration Head',
    'nav.signOut': 'Sign Out',
    'nav.profile': 'Profile',
    'admin.panel': 'Administration Head Panel',
    'admin.dashboard': 'Dashboard',
    'admin.orders': 'Orders',
    'admin.products': 'Products',
    'admin.offers': 'Offers',
    'admin.locations': 'Live Locations',
    'admin.role': 'ADMINISTRATION HEAD',
    'admin.backToStore': 'Back to Store',
    'admin.store': 'Store',
    'loading': 'Loading...',
    'home.specialOffers': 'Special Offers',
    'home.shopByCategory': 'Shop by Category',
    'home.lpgCylinders': 'LPG Cylinders',
    'home.bestSellers': 'Best Sellers',
    'home.services': 'Services',
    'home.bookNow': 'Book Now',
    'home.setDeliveryLocation': 'Set Delivery Location',
    'home.shareLocationText': 'Share your location for faster delivery',
    'products.title': 'Products & Services',
    'products.subtitle': 'Search LPG cylinders, stoves, burners, accessories and services',
    'products.searchPlaceholder': 'Search by product, company, size, valve or service...',
    'products.all': 'All',
    'products.lpgCylinders': 'LPG Cylinders',
    'products.stovesBurners': 'Stoves & Burners',
    'products.accessories': 'Accessories',
    'products.services': 'Services',
    'products.noProducts': 'No products found',
    'products.viewDetails': 'View Details',
    'cart.empty': 'Your cart is empty',
    'cart.emptySubtitle': 'Add some cylinders and products to get started',
    'cart.title': 'Shopping Cart',
    'cart.promoCode': 'Promo Code',
    'cart.orderSummary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.estimatedTotal': 'Estimated Total',
    'checkout.orderPlaced': 'Order Placed!',
    'checkout.confirmed': 'Your order has been confirmed and will be delivered soon.',
    'checkout.title': 'Checkout',
    'checkout.deliveryAddress': 'Delivery Address',
    'checkout.noSavedAddresses': 'No saved addresses',
    'checkout.deliveryFloor': 'Delivery Floor',
    'checkout.free': 'Free',
    'orders.title': 'My Orders',
    'orders.noOrders': 'No orders found',
    'orders.shareLocation': 'Share your location',
    'orders.sharingLocation': 'Sharing live location',
    'orders.locationHelp': 'Help us find you faster for delivery',
    'orders.locationLive': 'Delivery team can see you in real-time',
    'addresses.title': 'Delivery Addresses',
    'addresses.edit': 'Edit Address',
    'addresses.add': 'Add New Address',
    'profile.title': 'Profile Settings',
    'profile.edit': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.save': 'Save Changes',
    'profile.changePassword': 'Change Password',
    'profile.adminDashboard': 'Administration Head Dashboard',
    'offers.title': 'Special Offers',
    'offers.active': 'Active Offers',
    'offers.promoCodes': 'Promo Codes',
    'offers.none': 'No active offers right now',
    'offers.checkBack': 'Check back soon for exciting deals!',
    'product.notFound': 'Product not found',
    'product.home': 'Home',
    'product.products': 'Products',
    'product.company': 'Company',
    'product.size': 'Size',
    'product.valveSize': 'Valve Size',
    'product.valveType': 'Valve Type',
    'product.notes': 'Notes (Optional)',
    'product.quantity': 'Quantity:',
    'product.delivery': 'Delivery across Bangladesh',
    'type.new': 'New',
    'type.refill': 'Refill',
    'type.service': 'Service',
    'status.pending': 'Pending',
    'status.confirmed': 'Confirmed',
    'status.processing': 'Processing',
    'status.delivered': 'Delivered',
    'status.cancelled': 'Cancelled',
    'adminProducts.title': 'Products',
    'adminProducts.add': 'Add Product',
    'adminProducts.search': 'Search products, company, size, valve, services...',
    'adminProducts.noProducts': 'No products found',
    'adminOrders.title': 'Orders',
    'adminOrders.allStatuses': 'All Statuses',
    'adminOrders.noOrders': 'No orders found',
    'adminLocations.title': 'Live Customer Locations',
    'adminLocations.mapError': 'Google Map could not load',
    'adminLocations.loadingMap': 'Loading map...',
    'adminLocations.noCustomers': 'No customers sharing location',
    'adminLocations.noActiveShares': 'No active shares',
    'admin.users': 'Users & Employees',
    'common.back': 'Back',
    'notifications.title': 'Notifications',
    'notifications.open': 'Open notifications',
    'notifications.unreadCount': '{count} unread notifications',
    'notifications.noUnread': 'No unread notifications',
    'notifications.enableBrowser': 'Enable browser alerts',
    'notifications.markAllRead': 'Mark all read',
    'notifications.urgentAlert': 'Urgent alert',
    'notifications.empty': 'No notifications yet',
    'notifications.emptyText': 'Order, delivery and Administration Head alerts will appear here.',
    'notifications.new': 'NEW',
    'notifications.loadFailed': 'Failed to load notifications',
    'delivery.dashboard': 'HUB Man Dashboard',
    'delivery.sidebar': 'HUB Menu',
    'delivery.liveLocation': 'Live Location',
    'delivery.liveLocationHelp': 'Share your location after the Administration Head assigns orders to you.',
    'delivery.locationUnsupported': 'Location is not supported on this device/browser.',
    'delivery.allowLocation': 'Please allow location permission.',
    'delivery.locationUpdateFailed': 'Could not update live location.',
    'delivery.startSharing': 'Start Sharing Location',
    'delivery.stopSharing': 'Stop Sharing',
    'delivery.support': 'Delivery Support',
    'delivery.supportHelp': 'Call center numbers for any delivery problem.',
    'delivery.call': 'Call',
    'delivery.deliveredOrders': 'Delivered Orders',
    'delivery.deliveredOrdersHelp': 'Your completed delivery history and total delivered amount.',
    'delivery.totalDeliveredAmount': 'Total delivered amount',
    'delivery.noDeliveredOrders': 'No delivered orders yet.',
    'delivery.assignedActiveOrders': 'Assigned Active Orders',
    'delivery.assignedHelp': 'Only Administration Head-assigned orders appear here.',
    'delivery.loadingOrders': 'Loading orders...',
    'delivery.noAssignedOrders': 'No assigned active orders found.',
    'delivery.order': 'Order',
    'delivery.addressNotFound': 'Address not found',
    'delivery.customerRoutePoints': 'Customer route points',
    'delivery.available': 'available',
    'delivery.notSharing': 'not sharing',
    'delivery.routeView': 'Delivery Route View',
    'delivery.routeHelp': 'Green line: HUB man to customer. Blue line: customer shared route.',
    'delivery.customer': 'Customer',
    'delivery.amount': 'Amount',
    'delivery.status': 'Status',
    'delivery.updating': 'Updating...',
    'delivery.markDelivered': 'Mark Delivered',
    'footer.about': 'About Us',
    'footer.faq': 'FAQ',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.contact': 'Contact Us',
    'footer.description': 'Cylinder Express provides LPG cylinder ordering, delivery tracking, gas accessories, stove products and safety services for homes and businesses.',
    'footer.quickLinks': 'Quick Links',
    'footer.support': 'Support',
    'footer.location': 'Bangladesh',
    'footer.copyright': '© 2026 Cylinder Express. All rights reserved.',
    'about.title': 'About Us',
    'about.subtitle': 'Fast, safe and trackable LPG cylinder delivery for Bangladesh.',
    'about.intro': 'Cylinder Express is built to make LPG ordering easier, safer and more transparent for customers, the Administration Head, employees and delivery teams.',
    'about.point1': 'Customers can order LPG cylinders, stoves, burners, accessories and services from one web app.',
    'about.point2': 'The Administration Head and authorized employees can manage products, orders, service bookings, HUB personnel and live routes.',
    'about.point3': 'HUB Men can share live movement and complete assigned deliveries from their dashboard.',
    'about.point4': 'The system supports Bangla and English so users can work in their preferred language.',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Common answers about ordering, delivery, tracking and support.',
    'faq.intro': 'Here are the most common questions customers and business users ask about Cylinder Express.',
    'faq.q1': 'How do I place an order? Register or login, select your LPG cylinder/product/service, add it to cart and confirm checkout.',
    'faq.q2': 'Can I track delivery? Yes. After a HUB man is assigned, you can track delivery movement inside the My Orders page map.',
    'faq.q3': 'Can I book services? Yes. Gas stove installation, burner cleaning, pipe replacement and safety check services are supported.',
    'faq.q4': 'How are HUB personnel assigned? The Administration Head or an authorized employee can confirm orders and assign a nearby HUB man from the Orders page.',
    'faq.q5': 'Who do I call for support? Call +8801967517077 or +8801409472939 for support.',
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'How Cylinder Express handles customer, delivery and order information.',
    'privacy.intro': 'We collect only the information needed to operate ordering, delivery, safety, payment and support workflows.',
    'privacy.point1': 'We may store name, phone number, email, addresses, order history and service booking details.',
    'privacy.point2': 'Live location is used for active order delivery tracking and stops after delivery or cancellation.',
    'privacy.point3': 'Administration Head, employee and delivery location data is used for operational monitoring and assignment only.',
    'privacy.point4': 'We do not sell customer data to advertisers or unrelated third parties.',
    'privacy.point5': 'Users should keep account passwords private and contact support immediately for suspicious activity.',
    'terms.title': 'Terms of Use',
    'terms.subtitle': 'Rules for using Cylinder Express customer, Administration Head, employee and delivery services.',
    'terms.intro': 'By using Cylinder Express, users agree to provide accurate information and use the platform responsibly.',
    'terms.point1': 'Customers must provide correct phone number, delivery address and order information.',
    'terms.point2': 'Administration Head, employee and delivery accounts must not be shared with unauthorized people.',
    'terms.point3': 'Prices, offers and availability may change based on stock, delivery area and business policy.',
    'terms.point4': 'Live location features are for delivery operations and customer tracking only.',
    'terms.point5': 'Misuse, fraud, abuse or unauthorized access may lead to account restriction.',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Need help with orders, delivery, services or account access?',
    'contact.intro': 'Our support team can help with LPG orders, delivery tracking, service bookings, Administration Head access, employee access and delivery-person issues.',
    'contact.point1': 'Call center: +8801967517077',
    'contact.point2': 'Call center: +8801409472939',
    'contact.point3': 'Email: support@cylinderexpress.com',
    'contact.point4': 'For urgent delivery problems, call the support numbers directly.',
  },
  bn: {
    'language.label': 'ভাষা',
    'language.english': 'English',
    'language.bangla': 'বাংলা',
    'language.switchToBangla': 'বাংলা',
    'language.switchToEnglish': 'English',
    'nav.home': 'হোম',
    'nav.offers': 'অফার',
    'nav.products': 'পণ্য',
    'nav.cart': 'কার্ট',
    'nav.orders': 'অর্ডার',
    'nav.addresses': 'ঠিকানা',
    'nav.admin': 'অ্যাডমিনিস্ট্রেশন হেড',
    'nav.signOut': 'সাইন আউট',
    'nav.profile': 'প্রোফাইল',
    'admin.panel': 'অ্যাডমিনিস্ট্রেশন হেড প্যানেল',
    'admin.dashboard': 'ড্যাশবোর্ড',
    'admin.orders': 'অর্ডার',
    'admin.products': 'পণ্য',
    'admin.offers': 'অফার',
    'admin.locations': 'লাইভ লোকেশন',
    'admin.role': 'অ্যাডমিনিস্ট্রেশন হেড',
    'admin.backToStore': 'স্টোরে ফিরে যান',
    'admin.store': 'স্টোর',
    'loading': 'লোড হচ্ছে...',
    'home.specialOffers': 'বিশেষ অফার',
    'home.shopByCategory': 'ক্যাটাগরি অনুযায়ী কিনুন',
    'home.lpgCylinders': 'এলপিজি সিলিন্ডার',
    'home.bestSellers': 'বেস্ট সেলার',
    'home.services': 'সার্ভিসসমূহ',
    'home.bookNow': 'এখন বুক করুন',
    'home.setDeliveryLocation': 'ডেলিভারি লোকেশন সেট করুন',
    'home.shareLocationText': 'দ্রুত ডেলিভারির জন্য আপনার লোকেশন শেয়ার করুন',
    'products.title': 'পণ্য ও সার্ভিস',
    'products.subtitle': 'এলপিজি সিলিন্ডার, চুলা, বার্নার, এক্সেসরিজ ও সার্ভিস খুঁজুন',
    'products.searchPlaceholder': 'পণ্য, কোম্পানি, সাইজ, ভালভ বা সার্ভিস খুঁজুন...',
    'products.all': 'সব',
    'products.lpgCylinders': 'এলপিজি সিলিন্ডার',
    'products.stovesBurners': 'চুলা ও বার্নার',
    'products.accessories': 'এক্সেসরিজ',
    'products.services': 'সার্ভিস',
    'products.noProducts': 'কোনো পণ্য পাওয়া যায়নি',
    'products.viewDetails': 'বিস্তারিত দেখুন',
    'cart.empty': 'আপনার কার্ট খালি',
    'cart.emptySubtitle': 'শুরু করতে সিলিন্ডার ও পণ্য যোগ করুন',
    'cart.title': 'শপিং কার্ট',
    'cart.promoCode': 'প্রোমো কোড',
    'cart.orderSummary': 'অর্ডার সারাংশ',
    'cart.subtotal': 'সাবটোটাল',
    'cart.estimatedTotal': 'সম্ভাব্য মোট',
    'checkout.orderPlaced': 'অর্ডার হয়েছে!',
    'checkout.confirmed': 'আপনার অর্ডার নিশ্চিত হয়েছে এবং শীঘ্রই ডেলিভারি করা হবে।',
    'checkout.title': 'চেকআউট',
    'checkout.deliveryAddress': 'ডেলিভারি ঠিকানা',
    'checkout.noSavedAddresses': 'কোনো সংরক্ষিত ঠিকানা নেই',
    'checkout.deliveryFloor': 'ডেলিভারি ফ্লোর',
    'checkout.free': 'ফ্রি',
    'orders.title': 'আমার অর্ডার',
    'orders.noOrders': 'কোনো অর্ডার পাওয়া যায়নি',
    'orders.shareLocation': 'লোকেশন শেয়ার করুন',
    'orders.sharingLocation': 'লাইভ লোকেশন শেয়ার হচ্ছে',
    'orders.locationHelp': 'দ্রুত ডেলিভারির জন্য আমাদের আপনাকে খুঁজে পেতে সাহায্য করুন',
    'orders.locationLive': 'ডেলিভারি টিম রিয়েল-টাইমে আপনাকে দেখতে পারবে',
    'addresses.title': 'ডেলিভারি ঠিকানা',
    'addresses.edit': 'ঠিকানা সম্পাদনা',
    'addresses.add': 'নতুন ঠিকানা যোগ করুন',
    'profile.title': 'প্রোফাইল সেটিংস',
    'profile.edit': 'প্রোফাইল সম্পাদনা',
    'profile.fullName': 'পূর্ণ নাম',
    'profile.email': 'ইমেইল',
    'profile.phone': 'ফোন নম্বর',
    'profile.save': 'পরিবর্তন সংরক্ষণ',
    'profile.changePassword': 'পাসওয়ার্ড পরিবর্তন',
    'profile.adminDashboard': 'অ্যাডমিনিস্ট্রেশন হেড ড্যাশবোর্ড',
    'offers.title': 'বিশেষ অফার',
    'offers.active': 'চলমান অফার',
    'offers.promoCodes': 'প্রোমো কোড',
    'offers.none': 'এখন কোনো অফার নেই',
    'offers.checkBack': 'নতুন অফারের জন্য পরে আবার দেখুন!',
    'product.notFound': 'পণ্য পাওয়া যায়নি',
    'product.home': 'হোম',
    'product.products': 'পণ্য',
    'product.company': 'কোম্পানি',
    'product.size': 'সাইজ',
    'product.valveSize': 'ভালভ সাইজ',
    'product.valveType': 'ভালভ টাইপ',
    'product.notes': 'নোট (ঐচ্ছিক)',
    'product.quantity': 'পরিমাণ:',
    'product.delivery': 'বাংলাদেশজুড়ে ডেলিভারি',
    'type.new': 'নতুন',
    'type.refill': 'রিফিল',
    'type.service': 'সার্ভিস',
    'status.pending': 'পেন্ডিং',
    'status.confirmed': 'কনফার্মড',
    'status.processing': 'প্রসেসিং',
    'status.delivered': 'ডেলিভার্ড',
    'status.cancelled': 'ক্যানসেলড',
    'adminProducts.title': 'পণ্য',
    'adminProducts.add': 'পণ্য যোগ করুন',
    'adminProducts.search': 'পণ্য, কোম্পানি, সাইজ, ভালভ, সার্ভিস খুঁজুন...',
    'adminProducts.noProducts': 'কোনো পণ্য পাওয়া যায়নি',
    'adminOrders.title': 'অর্ডার',
    'adminOrders.allStatuses': 'সব স্ট্যাটাস',
    'adminOrders.noOrders': 'কোনো অর্ডার পাওয়া যায়নি',
    'adminLocations.title': 'লাইভ কাস্টমার লোকেশন',
    'adminLocations.mapError': 'গুগল ম্যাপ লোড হয়নি',
    'adminLocations.loadingMap': 'ম্যাপ লোড হচ্ছে...',
    'adminLocations.noCustomers': 'কোনো কাস্টমার লোকেশন শেয়ার করছেন না',
    'adminLocations.noActiveShares': 'কোনো অ্যাক্টিভ শেয়ার নেই',
    'admin.users': 'ইউজার ও কর্মচারী',
    'common.back': 'ফিরে যান',
    'notifications.title': 'নোটিফিকেশন',
    'notifications.open': 'নোটিফিকেশন খুলুন',
    'notifications.unreadCount': '{count}টি অপঠিত নোটিফিকেশন',
    'notifications.noUnread': 'কোনো অপঠিত নোটিফিকেশন নেই',
    'notifications.enableBrowser': 'ব্রাউজার অ্যালার্ট চালু করুন',
    'notifications.markAllRead': 'সব পড়া হয়েছে করুন',
    'notifications.urgentAlert': 'জরুরি অ্যালার্ট',
    'notifications.empty': 'এখনো কোনো নোটিফিকেশন নেই',
    'notifications.emptyText': 'অর্ডার, ডেলিভারি ও অ্যাডমিনিস্ট্রেশন হেড অ্যালার্ট এখানে দেখা যাবে।',
    'notifications.new': 'নতুন',
    'notifications.loadFailed': 'নোটিফিকেশন লোড করতে ব্যর্থ হয়েছে',
    'delivery.dashboard': 'হাব ম্যান ড্যাশবোর্ড',
    'delivery.sidebar': 'ডেলিভারি মেনু',
    'delivery.liveLocation': 'লাইভ লোকেশন',
    'delivery.liveLocationHelp': 'অ্যাডমিন অর্ডার অ্যাসাইন করার পর আপনার লোকেশন শেয়ার করুন।',
    'delivery.locationUnsupported': 'এই ডিভাইস/ব্রাউজারে লোকেশন সাপোর্ট নেই।',
    'delivery.allowLocation': 'অনুগ্রহ করে লোকেশন পারমিশন দিন।',
    'delivery.locationUpdateFailed': 'লাইভ লোকেশন আপডেট করা যায়নি।',
    'delivery.startSharing': 'লোকেশন শেয়ার শুরু করুন',
    'delivery.stopSharing': 'শেয়ার বন্ধ করুন',
    'delivery.support': 'ডেলিভারি সাপোর্ট',
    'delivery.supportHelp': 'ডেলিভারি সমস্যার জন্য কল সেন্টার নম্বর।',
    'delivery.call': 'কল করুন',
    'delivery.deliveredOrders': 'ডেলিভার্ড অর্ডার',
    'delivery.deliveredOrdersHelp': 'আপনার সম্পন্ন ডেলিভারি হিস্ট্রি এবং মোট ডেলিভারি অ্যামাউন্ট।',
    'delivery.totalDeliveredAmount': 'মোট ডেলিভার্ড অ্যামাউন্ট',
    'delivery.noDeliveredOrders': 'এখনো কোনো ডেলিভার্ড অর্ডার নেই।',
    'delivery.assignedActiveOrders': 'অ্যাসাইন করা সক্রিয় অর্ডার',
    'delivery.assignedHelp': 'শুধু অ্যাডমিন অ্যাসাইন করা অর্ডার এখানে দেখা যাবে।',
    'delivery.loadingOrders': 'অর্ডার লোড হচ্ছে...',
    'delivery.noAssignedOrders': 'কোনো অ্যাসাইন করা সক্রিয় অর্ডার পাওয়া যায়নি।',
    'delivery.order': 'অর্ডার',
    'delivery.addressNotFound': 'ঠিকানা পাওয়া যায়নি',
    'delivery.customerRoutePoints': 'কাস্টমার রুট পয়েন্ট',
    'delivery.available': 'আছে',
    'delivery.notSharing': 'শেয়ার করছে না',
    'delivery.routeView': 'ডেলিভারি রুট ভিউ',
    'delivery.routeHelp': 'সবুজ লাইন: হাব ম্যান থেকে কাস্টমার। নীল লাইন: কাস্টমারের শেয়ার করা রুট।',
    'delivery.customer': 'কাস্টমার',
    'delivery.amount': 'অ্যামাউন্ট',
    'delivery.status': 'স্ট্যাটাস',
    'delivery.updating': 'আপডেট হচ্ছে...',
    'delivery.markDelivered': 'ডেলিভার্ড করুন',
    'footer.about': 'আমাদের সম্পর্কে',
    'footer.faq': 'প্রশ্নোত্তর',
    'footer.privacy': 'প্রাইভেসি পলিসি',
    'footer.terms': 'ব্যবহারের শর্তাবলি',
    'footer.contact': 'যোগাযোগ করুন',
    'footer.description': 'Cylinder Express বাসা ও ব্যবসার জন্য এলপিজি সিলিন্ডার অর্ডার, ডেলিভারি ট্র্যাকিং, গ্যাস এক্সেসরিজ, চুলা পণ্য এবং সেফটি সার্ভিস প্রদান করে।',
    'footer.quickLinks': 'দ্রুত লিংক',
    'footer.support': 'সাপোর্ট',
    'footer.location': 'বাংলাদেশ',
    'footer.copyright': '© ২০২৬ Cylinder Express. সর্বস্বত্ব সংরক্ষিত।',
    'about.title': 'আমাদের সম্পর্কে',
    'about.subtitle': 'বাংলাদেশের জন্য দ্রুত, নিরাপদ ও ট্র্যাকযোগ্য এলপিজি সিলিন্ডার ডেলিভারি।',
    'about.intro': 'Cylinder Express কাস্টমার, অ্যাডমিন, সাব-অ্যাডমিন এবং ডেলিভারি টিমের জন্য এলপিজি অর্ডারিং সহজ, নিরাপদ এবং স্বচ্ছ করার জন্য তৈরি।',
    'about.point1': 'কাস্টমাররা একই ওয়েব অ্যাপ থেকে এলপিজি সিলিন্ডার, চুলা, বার্নার, এক্সেসরিজ এবং সার্ভিস অর্ডার করতে পারবেন।',
    'about.point2': 'অ্যাডমিন টিম পণ্য, অর্ডার, সার্ভিস বুকিং, হাব ম্যান এবং লাইভ রুট পরিচালনা করতে পারে।',
    'about.point3': 'হাব ম্যান নিজের লাইভ মুভমেন্ট শেয়ার করতে এবং অ্যাসাইন করা ডেলিভারি সম্পন্ন করতে পারে।',
    'about.point4': 'সিস্টেমটি বাংলা ও ইংরেজি সাপোর্ট করে যাতে ব্যবহারকারী পছন্দের ভাষায় কাজ করতে পারেন।',
    'faq.title': 'সচরাচর জিজ্ঞাসা',
    'faq.subtitle': 'অর্ডার, ডেলিভারি, ট্র্যাকিং এবং সাপোর্ট সম্পর্কে সাধারণ উত্তর।',
    'faq.intro': 'Cylinder Express সম্পর্কে কাস্টমার ও বিজনেস ইউজারদের সাধারণ প্রশ্নের উত্তর এখানে দেওয়া হলো।',
    'faq.q1': 'কীভাবে অর্ডার করব? রেজিস্টার বা লগইন করুন, এলপিজি সিলিন্ডার/পণ্য/সার্ভিস সিলেক্ট করে কার্টে যোগ করুন এবং চেকআউট নিশ্চিত করুন।',
    'faq.q2': 'ডেলিভারি ট্র্যাক করা যাবে? হ্যাঁ। হাব ম্যান অ্যাসাইন হলে My Orders পেজের ম্যাপের ভেতরেই মুভমেন্ট দেখা যাবে।',
    'faq.q3': 'সার্ভিস বুকিং করা যাবে? হ্যাঁ। গ্যাস চুলা ইনস্টলেশন, বার্নার ক্লিনিং, পাইপ রিপ্লেসমেন্ট এবং সেফটি চেক সার্ভিস সাপোর্টেড।',
    'faq.q4': 'অ্যাডমিন কীভাবে হাব ম্যান অ্যাসাইন করবে? অ্যাডমিন Orders পেজ থেকে অর্ডার কনফার্ম করে কাছাকাছি হাব ম্যান অ্যাসাইন করতে পারবে।',
    'faq.q5': 'সাপোর্টের জন্য কোথায় কল করব? +8801967517077 অথবা +8801409472939 নম্বরে কল করুন।',
    'privacy.title': 'প্রাইভেসি পলিসি',
    'privacy.subtitle': 'Cylinder Express কীভাবে কাস্টমার, ডেলিভারি ও অর্ডার তথ্য ব্যবহার করে।',
    'privacy.intro': 'অর্ডার, ডেলিভারি, সেফটি, পেমেন্ট ও সাপোর্ট চালানোর জন্য প্রয়োজনীয় তথ্যই আমরা সংগ্রহ করি।',
    'privacy.point1': 'আমরা নাম, ফোন নম্বর, ইমেইল, ঠিকানা, অর্ডার হিস্ট্রি এবং সার্ভিস বুকিং তথ্য সংরক্ষণ করতে পারি।',
    'privacy.point2': 'লাইভ লোকেশন সক্রিয় অর্ডার ডেলিভারি ট্র্যাকিংয়ের জন্য ব্যবহৃত হয় এবং ডেলিভারি বা ক্যানসেল হলে বন্ধ হয়।',
    'privacy.point3': 'অ্যাডমিন ও ডেলিভারি লোকেশন ডেটা শুধু অপারেশন মনিটরিং ও অ্যাসাইনমেন্টের জন্য ব্যবহৃত হয়।',
    'privacy.point4': 'আমরা কাস্টমার ডেটা বিজ্ঞাপনদাতা বা অপ্রাসঙ্গিক তৃতীয় পক্ষের কাছে বিক্রি করি না।',
    'privacy.point5': 'ব্যবহারকারীদের পাসওয়ার্ড গোপন রাখা উচিত এবং সন্দেহজনক কার্যক্রম দেখলে দ্রুত সাপোর্টে যোগাযোগ করতে হবে।',
    'terms.title': 'ব্যবহারের শর্তাবলি',
    'terms.subtitle': 'Cylinder Express কাস্টমার, অ্যাডমিন ও ডেলিভারি সার্ভিস ব্যবহারের নিয়ম।',
    'terms.intro': 'Cylinder Express ব্যবহার করলে ব্যবহারকারী সঠিক তথ্য প্রদান এবং দায়িত্বশীলভাবে প্ল্যাটফর্ম ব্যবহারে সম্মত হন।',
    'terms.point1': 'কাস্টমারকে সঠিক ফোন নম্বর, ডেলিভারি ঠিকানা এবং অর্ডার তথ্য দিতে হবে।',
    'terms.point2': 'অ্যাডমিন, সাব-অ্যাডমিন এবং ডেলিভারি অ্যাকাউন্ট অনুমতি ছাড়া অন্য কারও সাথে শেয়ার করা যাবে না।',
    'terms.point3': 'স্টক, ডেলিভারি এলাকা এবং বিজনেস পলিসির ভিত্তিতে দাম, অফার ও প্রাপ্যতা পরিবর্তন হতে পারে।',
    'terms.point4': 'লাইভ লোকেশন ফিচার শুধু ডেলিভারি অপারেশন এবং কাস্টমার ট্র্যাকিংয়ের জন্য।',
    'terms.point5': 'অপব্যবহার, প্রতারণা, অননুমোদিত প্রবেশ বা অ্যাবিউজ করলে অ্যাকাউন্ট সীমাবদ্ধ করা হতে পারে।',
    'contact.title': 'যোগাযোগ করুন',
    'contact.subtitle': 'অর্ডার, ডেলিভারি, সার্ভিস বা অ্যাকাউন্ট অ্যাক্সেসে সাহায্য লাগবে?',
    'contact.intro': 'আমাদের সাপোর্ট টিম এলপিজি অর্ডার, ডেলিভারি ট্র্যাকিং, সার্ভিস বুকিং, অ্যাডমিন অ্যাক্সেস এবং হাব ম্যান সমস্যায় সাহায্য করতে পারে।',
    'contact.point1': 'কল সেন্টার: +8801967517077',
    'contact.point2': 'কল সেন্টার: +8801409472939',
    'contact.point3': 'ইমেইল: support@cylinderexpress.com',
    'contact.point4': 'জরুরি ডেলিভারি সমস্যায় সরাসরি সাপোর্ট নম্বরে কল করুন।',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    const saved = window.localStorage.getItem(STORAGE_KEY);
    return saved === 'bn' || saved === 'en' ? saved : 'en';
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === 'bn' ? 'bn' : 'en';
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    toggleLanguage: () => setLanguageState((current) => (current === 'en' ? 'bn' : 'en')),
    t: (key: string) => translations[language][key] || translations.en[key] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
