import { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'en' | 'bn';

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const STORAGE_KEY = 'cylinder-express-language';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'language.label': 'Language',
    'language.english': 'English',
    'language.bangla': 'বাংলা',
    'language.switchToBangla': 'বাংলা',
    'language.switchToEnglish': 'English',
    'nav.home': 'Home',
    'nav.offers': 'Offers',
    'nav.products': 'Products',
    'nav.cart': 'Cart',
    'nav.orders': 'Orders',
    'nav.addresses': 'Addresses',
    'nav.admin': 'Admin',
    'nav.signOut': 'Sign Out',
    'nav.profile': 'Profile',
    'admin.panel': 'Admin Panel',
    'admin.dashboard': 'Dashboard',
    'admin.orders': 'Orders',
    'admin.products': 'Products',
    'admin.offers': 'Offers',
    'admin.locations': 'Live Locations',
    'admin.role': 'ADMIN',
    'admin.backToStore': 'Back to Store',
    'admin.store': 'Store',
    'loading': 'Loading...',
    'home.specialOffers': 'Special Offers',
    'home.shopByCategory': 'Shop by Category',
    'home.lpgCylinders': 'LPG Cylinders',
    'home.bestSellers': 'Best Sellers',
    'home.services': 'Services',
    'home.bookNow': 'Book Now',
    'home.setDeliveryLocation': 'Set Delivery Location',
    'home.shareLocationText': 'Share your location for faster delivery',
    'products.title': 'Products & Services',
    'products.subtitle': 'Search LPG cylinders, stoves, burners, accessories and services',
    'products.searchPlaceholder': 'Search by product, company, size, valve or service...',
    'products.all': 'All',
    'products.lpgCylinders': 'LPG Cylinders',
    'products.stovesBurners': 'Stoves & Burners',
    'products.accessories': 'Accessories',
    'products.services': 'Services',
    'products.noProducts': 'No products found',
    'products.viewDetails': 'View Details',
    'cart.empty': 'Your cart is empty',
    'cart.emptySubtitle': 'Add some cylinders and products to get started',
    'cart.title': 'Shopping Cart',
    'cart.promoCode': 'Promo Code',
    'cart.orderSummary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.estimatedTotal': 'Estimated Total',
    'checkout.orderPlaced': 'Order Placed!',
    'checkout.confirmed': 'Your order has been confirmed and will be delivered soon.',
    'checkout.title': 'Checkout',
    'checkout.deliveryAddress': 'Delivery Address',
    'checkout.noSavedAddresses': 'No saved addresses',
    'checkout.deliveryFloor': 'Delivery Floor',
    'checkout.free': 'Free',
    'orders.title': 'My Orders',
    'orders.noOrders': 'No orders found',
    'orders.shareLocation': 'Share your location',
    'orders.sharingLocation': 'Sharing live location',
    'orders.locationHelp': 'Help us find you faster for delivery',
    'orders.locationLive': 'Delivery team can see you in real-time',
    'addresses.title': 'Delivery Addresses',
    'addresses.edit': 'Edit Address',
    'addresses.add': 'Add New Address',
    'profile.title': 'Profile Settings',
    'profile.edit': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.save': 'Save Changes',
    'profile.changePassword': 'Change Password',
    'profile.adminDashboard': 'Admin Dashboard',
    'offers.title': 'Special Offers',
    'offers.active': 'Active Offers',
    'offers.promoCodes': 'Promo Codes',
    'offers.none': 'No active offers right now',
    'offers.checkBack': 'Check back soon for exciting deals!',
    'product.notFound': 'Product not found',
    'product.home': 'Home',
    'product.products': 'Products',
    'product.company': 'Company',
    'product.size': 'Size',
    'product.valveSize': 'Valve Size',
    'product.valveType': 'Valve Type',
    'product.notes': 'Notes (Optional)',
    'product.quantity': 'Quantity:',
    'product.delivery': 'Delivery across Bangladesh',
    'type.new': 'New',
    'type.refill': 'Refill',
    'type.service': 'Service',
    'status.pending': 'Pending',
    'status.confirmed': 'Confirmed',
    'status.processing': 'Processing',
    'status.delivered': 'Delivered',
    'status.cancelled': 'Cancelled',
    'adminProducts.title': 'Products',
    'adminProducts.add': 'Add Product',
    'adminProducts.search': 'Search products, company, size, valve, services...',
    'adminProducts.noProducts': 'No products found',
    'adminOrders.title': 'Orders',
    'adminOrders.allStatuses': 'All Statuses',
    'adminOrders.noOrders': 'No orders found',
    'adminLocations.title': 'Live Customer Locations',
    'adminLocations.mapError': 'Google Map could not load',
    'adminLocations.loadingMap': 'Loading map...',
    'adminLocations.noCustomers': 'No customers sharing location',
    'adminLocations.noActiveShares': 'No active shares',
    'nav.about': 'About Us',
    'nav.faq': 'FAQ',
    'nav.privacy': 'Privacy Policy',
    'nav.terms': 'Terms of Use',
    'nav.contact': 'Contact Us',
    'admin.users': 'Users & Sub-admins',
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Order, delivery and admin alerts',
    'notifications.empty': 'No notifications yet.',
    'notifications.new': 'NEW',
    'notifications.open': 'Open notifications',
    'notifications.urgentAlert': 'Urgent alert',
    'notifications.enableBrowserAlerts': 'Enable browser alerts',
    'notifications.markAllRead': 'Mark all read',
    'about.title': 'About Cylinder Express',
    'about.subtitle': 'Cylinder Express is a smart LPG delivery, product, and service platform built to make gas ordering safer, faster, and easier for households and businesses.',
    'about.heroNote': 'Reliable LPG delivery with digital tracking',
    'about.section1.title': 'Who we are',
    'about.section1.body1': 'Cylinder Express connects customers with LPG cylinders, stoves, burners, accessories, safety services, and delivery support from one digital platform.',
    'about.section1.body2': 'Our goal is to reduce manual order confusion, improve delivery visibility, and help customers receive gas-related products and services with confidence.',
    'about.section2.title': 'What we provide',
    'about.section2.body1': 'Customers can order LPG cylinder refills, new cylinders, regulators, pipes, burners, stoves, and related accessories directly from the app.',
    'about.section2.body2': 'The platform also supports service bookings such as stove installation, burner cleaning, gas leak safety checks, regulator replacement, and emergency gas support.',
    'about.section3.title': 'Our operation promise',
    'about.section3.body1': 'Admin teams can monitor orders, assign delivery men, track live movement, and manage products, offers, users, and service requests from the dashboard.',
    'about.section3.body2': 'We focus on speed, safety, transparency, and practical business control for LPG delivery operations.',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find quick answers about ordering, delivery tracking, service bookings, payment, and support.',
    'faq.q1': 'How can I place an LPG order?',
    'faq.a1': 'Login, choose your LPG company and cylinder size, add the item to cart, select your delivery address and floor, then confirm checkout.',
    'faq.q2': 'Can I book gas stove or burner services?',
    'faq.a2': 'Yes. You can book services such as stove installation, burner cleaning, gas leak checks, pipe replacement, and regulator replacement from the products and services page.',
    'faq.q3': 'How does live delivery tracking work?',
    'faq.a3': 'After an order is placed, customer live location can start for delivery support. Once a delivery man is assigned, the customer can track the delivery man movement inside the order page map.',
    'faq.q4': 'When does location sharing stop?',
    'faq.a4': 'Location sharing stops when the order is delivered or cancelled. After admin confirmation, customer location sharing is controlled by the active order workflow.',
    'faq.q5': 'Can I contact support?',
    'faq.a5': 'Yes. You can call the call center numbers from the contact page or from delivery support screens.',
    'faq.q6': 'Can admin manage delivery men?',
    'faq.a6': 'Yes. Admin and permitted sub-admins can create delivery man accounts, save permanent base locations, assign nearby delivery men, and view delivery reports.',
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'This policy explains how Cylinder Express handles customer, admin, sub-admin, and delivery information inside the platform.',
    'privacy.heroNote': 'Your information is used to complete LPG orders and services safely.',
    'privacy.section1.title': 'Information we collect',
    'privacy.section1.body1': 'We collect account information such as name, phone number, optional email, address, login details, order details, service booking details, and profile photo if uploaded.',
    'privacy.section1.body2': 'For delivery operations, the platform may collect live customer location and delivery man location while an active order is being processed.',
    'privacy.section2.title': 'How we use information',
    'privacy.section2.body1': 'We use information to create accounts, verify phone numbers, process orders, assign delivery men, show route tracking, manage service bookings, and provide support.',
    'privacy.section2.body2': 'Admin and authorized sub-admins may access operational data only for managing orders, users, products, delivery, and customer support.',
    'privacy.section3.title': 'Location data',
    'privacy.section3.body1': 'Live location is used to help delivery teams find customers and to let customers track assigned delivery movement inside the app.',
    'privacy.section3.body2': 'Location sharing is stopped after delivery or cancellation according to the order workflow.',
    'privacy.section4.title': 'Data protection',
    'privacy.section4.body1': 'We recommend using strong passwords, secured hosting environment variables, restricted API keys, and controlled admin permissions to protect business and customer data.',
    'terms.title': 'Terms of Use',
    'terms.subtitle': 'These terms describe the basic rules for using Cylinder Express customer, admin, sub-admin, and delivery features.',
    'terms.heroNote': 'Use the platform responsibly and keep account information secure.',
    'terms.section1.title': 'Account use',
    'terms.section1.body1': 'Users must provide valid phone numbers and accurate information during registration, order placement, service booking, and delivery operations.',
    'terms.section1.body2': 'Admins, sub-admins, and delivery men are responsible for protecting their login credentials and using access only for authorized business work.',
    'terms.section2.title': 'Orders and services',
    'terms.section2.body1': 'Product availability, delivery timing, service timing, and pricing may depend on operational capacity, location, and admin confirmation.',
    'terms.section2.body2': 'Customers should provide correct delivery address, floor information, and phone number so the delivery team can complete the order properly.',
    'terms.section3.title': 'Tracking and notifications',
    'terms.section3.body1': 'The platform may use live location, route tracking, browser notifications, SMS, and alert sounds to support order delivery and admin operations.',
    'terms.section3.body2': 'Browser permissions may be required for location, notification, vibration, or sound features to work correctly.',
    'terms.section4.title': 'Misuse',
    'terms.section4.body1': 'Accounts may be restricted if used for false orders, unauthorized access, abusive behavior, or activity that harms customers, delivery teams, or business operations.',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Need help with an order, delivery, service booking, or account issue? Contact Cylinder Express support.',
    'contact.phone1': 'Call Center 1',
    'contact.phone2': 'Call Center 2',
    'contact.email': 'Support Email',
    'contact.support': 'Order Support',
    'contact.supportValue': 'Check My Orders',
    'contact.officeTitle': 'Service Area & Support',
    'contact.officeBody': 'Cylinder Express support teams handle LPG orders, product support, service bookings, delivery coordination, and customer assistance through the platform and call center.',
  },
  bn: {
    'language.label': 'ভাষা',
    'language.english': 'English',
    'language.bangla': 'বাংলা',
    'language.switchToBangla': 'বাংলা',
    'language.switchToEnglish': 'English',
    'nav.home': 'হোম',
    'nav.offers': 'অফার',
    'nav.products': 'পণ্য',
    'nav.cart': 'কার্ট',
    'nav.orders': 'অর্ডার',
    'nav.addresses': 'ঠিকানা',
    'nav.admin': 'অ্যাডমিন',
    'nav.signOut': 'সাইন আউট',
    'nav.profile': 'প্রোফাইল',
    'admin.panel': 'অ্যাডমিন প্যানেল',
    'admin.dashboard': 'ড্যাশবোর্ড',
    'admin.orders': 'অর্ডার',
    'admin.products': 'পণ্য',
    'admin.offers': 'অফার',
    'admin.locations': 'লাইভ লোকেশন',
    'admin.role': 'অ্যাডমিন',
    'admin.backToStore': 'স্টোরে ফিরে যান',
    'admin.store': 'স্টোর',
    'loading': 'লোড হচ্ছে...',
    'home.specialOffers': 'বিশেষ অফার',
    'home.shopByCategory': 'ক্যাটাগরি অনুযায়ী কিনুন',
    'home.lpgCylinders': 'এলপিজি সিলিন্ডার',
    'home.bestSellers': 'বেস্ট সেলার',
    'home.services': 'সার্ভিসসমূহ',
    'home.bookNow': 'এখন বুক করুন',
    'home.setDeliveryLocation': 'ডেলিভারি লোকেশন সেট করুন',
    'home.shareLocationText': 'দ্রুত ডেলিভারির জন্য আপনার লোকেশন শেয়ার করুন',
    'products.title': 'পণ্য ও সার্ভিস',
    'products.subtitle': 'এলপিজি সিলিন্ডার, চুলা, বার্নার, এক্সেসরিজ ও সার্ভিস খুঁজুন',
    'products.searchPlaceholder': 'পণ্য, কোম্পানি, সাইজ, ভালভ বা সার্ভিস খুঁজুন...',
    'products.all': 'সব',
    'products.lpgCylinders': 'এলপিজি সিলিন্ডার',
    'products.stovesBurners': 'চুলা ও বার্নার',
    'products.accessories': 'এক্সেসরিজ',
    'products.services': 'সার্ভিস',
    'products.noProducts': 'কোনো পণ্য পাওয়া যায়নি',
    'products.viewDetails': 'বিস্তারিত দেখুন',
    'cart.empty': 'আপনার কার্ট খালি',
    'cart.emptySubtitle': 'শুরু করতে সিলিন্ডার ও পণ্য যোগ করুন',
    'cart.title': 'শপিং কার্ট',
    'cart.promoCode': 'প্রোমো কোড',
    'cart.orderSummary': 'অর্ডার সারাংশ',
    'cart.subtotal': 'সাবটোটাল',
    'cart.estimatedTotal': 'সম্ভাব্য মোট',
    'checkout.orderPlaced': 'অর্ডার হয়েছে!',
    'checkout.confirmed': 'আপনার অর্ডার নিশ্চিত হয়েছে এবং শীঘ্রই ডেলিভারি করা হবে।',
    'checkout.title': 'চেকআউট',
    'checkout.deliveryAddress': 'ডেলিভারি ঠিকানা',
    'checkout.noSavedAddresses': 'কোনো সংরক্ষিত ঠিকানা নেই',
    'checkout.deliveryFloor': 'ডেলিভারি ফ্লোর',
    'checkout.free': 'ফ্রি',
    'orders.title': 'আমার অর্ডার',
    'orders.noOrders': 'কোনো অর্ডার পাওয়া যায়নি',
    'orders.shareLocation': 'লোকেশন শেয়ার করুন',
    'orders.sharingLocation': 'লাইভ লোকেশন শেয়ার হচ্ছে',
    'orders.locationHelp': 'দ্রুত ডেলিভারির জন্য আমাদের আপনাকে খুঁজে পেতে সাহায্য করুন',
    'orders.locationLive': 'ডেলিভারি টিম রিয়েল-টাইমে আপনাকে দেখতে পারবে',
    'addresses.title': 'ডেলিভারি ঠিকানা',
    'addresses.edit': 'ঠিকানা সম্পাদনা',
    'addresses.add': 'নতুন ঠিকানা যোগ করুন',
    'profile.title': 'প্রোফাইল সেটিংস',
    'profile.edit': 'প্রোফাইল সম্পাদনা',
    'profile.fullName': 'পূর্ণ নাম',
    'profile.email': 'ইমেইল',
    'profile.phone': 'ফোন নম্বর',
    'profile.save': 'পরিবর্তন সংরক্ষণ',
    'profile.changePassword': 'পাসওয়ার্ড পরিবর্তন',
    'profile.adminDashboard': 'অ্যাডমিন ড্যাশবোর্ড',
    'offers.title': 'বিশেষ অফার',
    'offers.active': 'চলমান অফার',
    'offers.promoCodes': 'প্রোমো কোড',
    'offers.none': 'এখন কোনো অফার নেই',
    'offers.checkBack': 'নতুন অফারের জন্য পরে আবার দেখুন!',
    'product.notFound': 'পণ্য পাওয়া যায়নি',
    'product.home': 'হোম',
    'product.products': 'পণ্য',
    'product.company': 'কোম্পানি',
    'product.size': 'সাইজ',
    'product.valveSize': 'ভালভ সাইজ',
    'product.valveType': 'ভালভ টাইপ',
    'product.notes': 'নোট (ঐচ্ছিক)',
    'product.quantity': 'পরিমাণ:',
    'product.delivery': 'বাংলাদেশজুড়ে ডেলিভারি',
    'type.new': 'নতুন',
    'type.refill': 'রিফিল',
    'type.service': 'সার্ভিস',
    'status.pending': 'পেন্ডিং',
    'status.confirmed': 'কনফার্মড',
    'status.processing': 'প্রসেসিং',
    'status.delivered': 'ডেলিভার্ড',
    'status.cancelled': 'ক্যানসেলড',
    'adminProducts.title': 'পণ্য',
    'adminProducts.add': 'পণ্য যোগ করুন',
    'adminProducts.search': 'পণ্য, কোম্পানি, সাইজ, ভালভ, সার্ভিস খুঁজুন...',
    'adminProducts.noProducts': 'কোনো পণ্য পাওয়া যায়নি',
    'adminOrders.title': 'অর্ডার',
    'adminOrders.allStatuses': 'সব স্ট্যাটাস',
    'adminOrders.noOrders': 'কোনো অর্ডার পাওয়া যায়নি',
    'adminLocations.title': 'লাইভ কাস্টমার লোকেশন',
    'adminLocations.mapError': 'গুগল ম্যাপ লোড হয়নি',
    'adminLocations.loadingMap': 'ম্যাপ লোড হচ্ছে...',
    'adminLocations.noCustomers': 'কোনো কাস্টমার লোকেশন শেয়ার করছেন না',
    'adminLocations.noActiveShares': 'কোনো অ্যাক্টিভ শেয়ার নেই',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.faq': 'প্রশ্নোত্তর',
    'nav.privacy': 'প্রাইভেসি পলিসি',
    'nav.terms': 'ব্যবহারের শর্তাবলী',
    'nav.contact': 'যোগাযোগ',
    'admin.users': 'ইউজার ও সাব-অ্যাডমিন',
    'notifications.title': 'নোটিফিকেশন',
    'notifications.subtitle': 'অর্ডার, ডেলিভারি ও অ্যাডমিন অ্যালার্ট',
    'notifications.empty': 'এখনো কোনো নোটিফিকেশন নেই।',
    'notifications.new': 'নতুন',
    'notifications.open': 'নোটিফিকেশন খুলুন',
    'notifications.urgentAlert': 'জরুরি অ্যালার্ট',
    'notifications.enableBrowserAlerts': 'ব্রাউজার অ্যালার্ট চালু করুন',
    'notifications.markAllRead': 'সব পড়া হয়েছে করুন',
    'about.title': 'Cylinder Express সম্পর্কে',
    'about.subtitle': 'Cylinder Express একটি স্মার্ট এলপিজি ডেলিভারি, পণ্য এবং সার্ভিস প্ল্যাটফর্ম; যা ঘর ও ব্যবসার জন্য গ্যাস অর্ডারকে নিরাপদ, দ্রুত এবং সহজ করে।',
    'about.heroNote': 'ডিজিটাল ট্র্যাকিংসহ নির্ভরযোগ্য এলপিজি ডেলিভারি',
    'about.section1.title': 'আমরা কারা',
    'about.section1.body1': 'Cylinder Express এক প্ল্যাটফর্মে এলপিজি সিলিন্ডার, চুলা, বার্নার, এক্সেসরিজ, সেফটি সার্ভিস এবং ডেলিভারি সাপোর্টের সাথে কাস্টমারকে যুক্ত করে।',
    'about.section1.body2': 'আমাদের লক্ষ্য হলো ম্যানুয়াল অর্ডার বিভ্রান্তি কমানো, ডেলিভারি দৃশ্যমানতা বাড়ানো এবং আত্মবিশ্বাসের সাথে গ্যাস-সম্পর্কিত পণ্য ও সার্ভিস পৌঁছে দেওয়া।',
    'about.section2.title': 'আমরা কী দিই',
    'about.section2.body1': 'কাস্টমার অ্যাপ থেকে এলপিজি সিলিন্ডার রিফিল, নতুন সিলিন্ডার, রেগুলেটর, পাইপ, বার্নার, চুলা ও এক্সেসরিজ অর্ডার করতে পারেন।',
    'about.section2.body2': 'চুলা ইনস্টলেশন, বার্নার ক্লিনিং, গ্যাস লিক সেফটি চেক, রেগুলেটর রিপ্লেসমেন্ট এবং জরুরি গ্যাস সাপোর্ট বুকিংও করা যায়।',
    'about.section3.title': 'আমাদের অপারেশন প্রতিশ্রুতি',
    'about.section3.body1': 'অ্যাডমিন টিম অর্ডার মনিটর, ডেলিভারি ম্যান অ্যাসাইন, লাইভ মুভমেন্ট ট্র্যাক এবং পণ্য, অফার, ইউজার ও সার্ভিস রিকোয়েস্ট পরিচালনা করতে পারে।',
    'about.section3.body2': 'আমরা এলপিজি ডেলিভারি অপারেশনে গতি, নিরাপত্তা, স্বচ্ছতা এবং বাস্তব ব্যবসায়িক কন্ট্রোলকে গুরুত্ব দিই।',
    'faq.title': 'সাধারণ প্রশ্নোত্তর',
    'faq.subtitle': 'অর্ডার, ডেলিভারি ট্র্যাকিং, সার্ভিস বুকিং, পেমেন্ট ও সাপোর্ট সম্পর্কে দ্রুত উত্তর দেখুন।',
    'faq.q1': 'আমি কীভাবে এলপিজি অর্ডার করব?',
    'faq.a1': 'লগইন করে এলপিজি কোম্পানি ও সিলিন্ডার সাইজ নির্বাচন করুন, কার্টে যোগ করুন, ডেলিভারি ঠিকানা ও ফ্লোর নির্বাচন করে চেকআউট কনফার্ম করুন।',
    'faq.q2': 'গ্যাস চুলা বা বার্নার সার্ভিস বুক করা যাবে?',
    'faq.a2': 'হ্যাঁ। পণ্য ও সার্ভিস পেজ থেকে চুলা ইনস্টলেশন, বার্নার ক্লিনিং, গ্যাস লিক চেক, পাইপ রিপ্লেসমেন্ট ও রেগুলেটর রিপ্লেসমেন্ট বুক করা যাবে।',
    'faq.q3': 'লাইভ ডেলিভারি ট্র্যাকিং কীভাবে কাজ করে?',
    'faq.a3': 'অর্ডার করার পর ডেলিভারি সাপোর্টের জন্য কাস্টমার লাইভ লোকেশন শুরু হতে পারে। ডেলিভারি ম্যান অ্যাসাইন হলে কাস্টমার অর্ডার পেজের ম্যাপের ভেতরে তার মুভমেন্ট দেখতে পারেন।',
    'faq.q4': 'লোকেশন শেয়ারিং কখন বন্ধ হয়?',
    'faq.a4': 'অর্ডার ডেলিভার্ড বা ক্যানসেল হলে লোকেশন শেয়ারিং বন্ধ হয়। অ্যাডমিন কনফার্ম করার পর কাস্টমার লোকেশন শেয়ারিং অ্যাক্টিভ অর্ডার ওয়ার্কফ্লো দ্বারা নিয়ন্ত্রিত হয়।',
    'faq.q5': 'আমি কি সাপোর্টে যোগাযোগ করতে পারি?',
    'faq.a5': 'হ্যাঁ। যোগাযোগ পেজ অথবা ডেলিভারি সাপোর্ট স্ক্রিন থেকে কল সেন্টার নম্বরে কল করতে পারবেন।',
    'faq.q6': 'অ্যাডমিন কি ডেলিভারি ম্যান ম্যানেজ করতে পারে?',
    'faq.a6': 'হ্যাঁ। অ্যাডমিন ও অনুমোদিত সাব-অ্যাডমিন ডেলিভারি ম্যান অ্যাকাউন্ট তৈরি, পার্মানেন্ট বেস লোকেশন সেভ, কাছের ডেলিভারি ম্যান অ্যাসাইন এবং ডেলিভারি রিপোর্ট দেখতে পারে।',
    'privacy.title': 'প্রাইভেসি পলিসি',
    'privacy.subtitle': 'এই পলিসি ব্যাখ্যা করে Cylinder Express কীভাবে কাস্টমার, অ্যাডমিন, সাব-অ্যাডমিন ও ডেলিভারি তথ্য ব্যবহার করে।',
    'privacy.heroNote': 'আপনার তথ্য নিরাপদভাবে এলপিজি অর্ডার ও সার্ভিস সম্পন্ন করতে ব্যবহার করা হয়।',
    'privacy.section1.title': 'আমরা যে তথ্য সংগ্রহ করি',
    'privacy.section1.body1': 'আমরা নাম, ফোন নম্বর, ঐচ্ছিক ইমেইল, ঠিকানা, লগইন তথ্য, অর্ডার তথ্য, সার্ভিস বুকিং তথ্য এবং আপলোড করা হলে প্রোফাইল ছবি সংগ্রহ করি।',
    'privacy.section1.body2': 'ডেলিভারি অপারেশনের জন্য অ্যাক্টিভ অর্ডার চলাকালে কাস্টমার লাইভ লোকেশন ও ডেলিভারি ম্যান লোকেশন সংগ্রহ হতে পারে।',
    'privacy.section2.title': 'তথ্য কীভাবে ব্যবহার করি',
    'privacy.section2.body1': 'অ্যাকাউন্ট তৈরি, ফোন যাচাই, অর্ডার প্রসেস, ডেলিভারি ম্যান অ্যাসাইন, রুট ট্র্যাকিং, সার্ভিস বুকিং এবং সাপোর্টের জন্য তথ্য ব্যবহার করা হয়।',
    'privacy.section2.body2': 'অ্যাডমিন ও অনুমোদিত সাব-অ্যাডমিন শুধু অর্ডার, ইউজার, পণ্য, ডেলিভারি ও কাস্টমার সাপোর্ট পরিচালনার জন্য অপারেশনাল তথ্য দেখতে পারে।',
    'privacy.section3.title': 'লোকেশন ডেটা',
    'privacy.section3.body1': 'লাইভ লোকেশন ডেলিভারি টিমকে কাস্টমার খুঁজে পেতে এবং কাস্টমারকে অ্যাপের ভেতরে অ্যাসাইনড ডেলিভারি মুভমেন্ট দেখতে সাহায্য করে।',
    'privacy.section3.body2': 'অর্ডার ডেলিভারি বা ক্যানসেল হওয়ার পর অর্ডার ওয়ার্কফ্লো অনুযায়ী লোকেশন শেয়ারিং বন্ধ হয়।',
    'privacy.section4.title': 'ডেটা সুরক্ষা',
    'privacy.section4.body1': 'ব্যবসা ও কাস্টমার ডেটা সুরক্ষার জন্য শক্তিশালী পাসওয়ার্ড, সুরক্ষিত হোস্টিং এনভায়রনমেন্ট ভ্যারিয়েবল, সীমিত API key এবং নিয়ন্ত্রিত অ্যাডমিন পারমিশন ব্যবহার করার পরামর্শ দিই।',
    'terms.title': 'ব্যবহারের শর্তাবলী',
    'terms.subtitle': 'এই শর্তাবলী Cylinder Express এর কাস্টমার, অ্যাডমিন, সাব-অ্যাডমিন ও ডেলিভারি ফিচার ব্যবহারের মৌলিক নিয়ম বর্ণনা করে।',
    'terms.heroNote': 'দায়িত্বশীলভাবে প্ল্যাটফর্ম ব্যবহার করুন এবং অ্যাকাউন্ট তথ্য নিরাপদ রাখুন।',
    'terms.section1.title': 'অ্যাকাউন্ট ব্যবহার',
    'terms.section1.body1': 'রেজিস্ট্রেশন, অর্ডার, সার্ভিস বুকিং ও ডেলিভারি অপারেশনের সময় ইউজারদের সঠিক ফোন নম্বর ও তথ্য দিতে হবে।',
    'terms.section1.body2': 'অ্যাডমিন, সাব-অ্যাডমিন ও ডেলিভারি ম্যান তাদের লগইন তথ্য সুরক্ষিত রাখা এবং শুধুমাত্র অনুমোদিত ব্যবসায়িক কাজে অ্যাক্সেস ব্যবহার করার জন্য দায়ী।',
    'terms.section2.title': 'অর্ডার ও সার্ভিস',
    'terms.section2.body1': 'পণ্যের প্রাপ্যতা, ডেলিভারি সময়, সার্ভিস সময় এবং মূল্য অপারেশন ক্ষমতা, লোকেশন ও অ্যাডমিন কনফার্মেশনের উপর নির্ভর করতে পারে।',
    'terms.section2.body2': 'সঠিক ডেলিভারির জন্য কাস্টমারকে সঠিক ঠিকানা, ফ্লোর তথ্য এবং ফোন নম্বর দিতে হবে।',
    'terms.section3.title': 'ট্র্যাকিং ও নোটিফিকেশন',
    'terms.section3.body1': 'অর্ডার ডেলিভারি ও অ্যাডমিন অপারেশনের জন্য প্ল্যাটফর্ম লাইভ লোকেশন, রুট ট্র্যাকিং, ব্রাউজার নোটিফিকেশন, SMS এবং অ্যালার্ট সাউন্ড ব্যবহার করতে পারে।',
    'terms.section3.body2': 'লোকেশন, নোটিফিকেশন, ভাইব্রেশন বা সাউন্ড ফিচার ঠিকভাবে কাজ করতে ব্রাউজার পারমিশন প্রয়োজন হতে পারে।',
    'terms.section4.title': 'অপব্যবহার',
    'terms.section4.body1': 'ভুয়া অর্ডার, অননুমোদিত অ্যাক্সেস, অপমানজনক আচরণ বা কাস্টমার, ডেলিভারি টিম বা ব্যবসায়িক অপারেশনের ক্ষতি করলে অ্যাকাউন্ট সীমাবদ্ধ করা হতে পারে।',
    'contact.title': 'যোগাযোগ করুন',
    'contact.subtitle': 'অর্ডার, ডেলিভারি, সার্ভিস বুকিং বা অ্যাকাউন্ট সমস্যায় সাহায্য দরকার? Cylinder Express সাপোর্টে যোগাযোগ করুন।',
    'contact.phone1': 'কল সেন্টার ১',
    'contact.phone2': 'কল সেন্টার ২',
    'contact.email': 'সাপোর্ট ইমেইল',
    'contact.support': 'অর্ডার সাপোর্ট',
    'contact.supportValue': 'আমার অর্ডার দেখুন',
    'contact.officeTitle': 'সার্ভিস এলাকা ও সাপোর্ট',
    'contact.officeBody': 'Cylinder Express সাপোর্ট টিম প্ল্যাটফর্ম ও কল সেন্টারের মাধ্যমে এলপিজি অর্ডার, পণ্য সাপোর্ট, সার্ভিস বুকিং, ডেলিভারি সমন্বয় এবং কাস্টমার সহায়তা পরিচালনা করে।',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    const saved = window.localStorage.getItem(STORAGE_KEY);
    return saved === 'bn' || saved === 'en' ? saved : 'en';
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === 'bn' ? 'bn' : 'en';
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    toggleLanguage: () => setLanguageState((current) => (current === 'en' ? 'bn' : 'en')),
    t: (key: string) => translations[language][key] || translations.en[key] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
