import { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'en' | 'bn';

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const STORAGE_KEY = 'cylinder-express-language';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'language.label': 'Language',
    'language.english': 'English',
    'language.bangla': 'বাংলা',
    'language.switchToBangla': 'বাংলা',
    'language.switchToEnglish': 'English',
    'nav.home': 'Home',
    'nav.offers': 'Offers',
    'nav.products': 'Products',
    'nav.cart': 'Cart',
    'nav.orders': 'Orders',
    'nav.addresses': 'Addresses',
    'nav.admin': 'Admin',
    'nav.signOut': 'Sign Out',
    'nav.profile': 'Profile',
    'admin.panel': 'Admin Panel',
    'admin.dashboard': 'Dashboard',
    'admin.orders': 'Orders',
    'admin.products': 'Products',
    'admin.offers': 'Offers',
    'admin.locations': 'Live Locations',
    'admin.role': 'ADMIN',
    'admin.backToStore': 'Back to Store',
    'admin.store': 'Store',
    'loading': 'Loading...',
    'home.specialOffers': 'Special Offers',
    'home.shopByCategory': 'Shop by Category',
    'home.lpgCylinders': 'LPG Cylinders',
    'home.bestSellers': 'Best Sellers',
    'home.services': 'Services',
    'home.bookNow': 'Book Now',
    'home.setDeliveryLocation': 'Set Delivery Location',
    'home.shareLocationText': 'Share your location for faster delivery',
    'products.title': 'Products & Services',
    'products.subtitle': 'Search LPG cylinders, stoves, burners, accessories and services',
    'products.searchPlaceholder': 'Search by product, company, size, valve or service...',
    'products.all': 'All',
    'products.lpgCylinders': 'LPG Cylinders',
    'products.stovesBurners': 'Stoves & Burners',
    'products.accessories': 'Accessories',
    'products.services': 'Services',
    'products.noProducts': 'No products found',
    'products.viewDetails': 'View Details',
    'cart.empty': 'Your cart is empty',
    'cart.emptySubtitle': 'Add some cylinders and products to get started',
    'cart.title': 'Shopping Cart',
    'cart.promoCode': 'Promo Code',
    'cart.orderSummary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.estimatedTotal': 'Estimated Total',
    'checkout.orderPlaced': 'Order Placed!',
    'checkout.confirmed': 'Your order has been confirmed and will be delivered soon.',
    'checkout.title': 'Checkout',
    'checkout.deliveryAddress': 'Delivery Address',
    'checkout.noSavedAddresses': 'No saved addresses',
    'checkout.deliveryFloor': 'Delivery Floor',
    'checkout.free': 'Free',
    'orders.title': 'My Orders',
    'orders.noOrders': 'No orders found',
    'orders.shareLocation': 'Share your location',
    'orders.sharingLocation': 'Sharing live location',
    'orders.locationHelp': 'Help us find you faster for delivery',
    'orders.locationLive': 'Delivery team can see you in real-time',
    'addresses.title': 'Delivery Addresses',
    'addresses.edit': 'Edit Address',
    'addresses.add': 'Add New Address',
    'profile.title': 'Profile Settings',
    'profile.edit': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.save': 'Save Changes',
    'profile.changePassword': 'Change Password',
    'profile.adminDashboard': 'Admin Dashboard',
    'offers.title': 'Special Offers',
    'offers.active': 'Active Offers',
    'offers.promoCodes': 'Promo Codes',
    'offers.none': 'No active offers right now',
    'offers.checkBack': 'Check back soon for exciting deals!',
    'product.notFound': 'Product not found',
    'product.home': 'Home',
    'product.products': 'Products',
    'product.company': 'Company',
    'product.size': 'Size',
    'product.valveSize': 'Valve Size',
    'product.valveType': 'Valve Type',
    'product.notes': 'Notes (Optional)',
    'product.quantity': 'Quantity:',
    'product.delivery': 'Delivery across Bangladesh',
    'type.new': 'New',
    'type.refill': 'Refill',
    'type.service': 'Service',
    'status.pending': 'Pending',
    'status.confirmed': 'Confirmed',
    'status.processing': 'Processing',
    'status.delivered': 'Delivered',
    'status.cancelled': 'Cancelled',
    'adminProducts.title': 'Products',
    'adminProducts.add': 'Add Product',
    'adminProducts.search': 'Search products, company, size, valve, services...',
    'adminProducts.noProducts': 'No products found',
    'adminOrders.title': 'Orders',
    'adminOrders.allStatuses': 'All Statuses',
    'adminOrders.noOrders': 'No orders found',
    'adminLocations.title': 'Live Customer Locations',
    'adminLocations.mapError': 'Google Map could not load',
    'adminLocations.loadingMap': 'Loading map...',
    'adminLocations.noCustomers': 'No customers sharing location',
    'adminLocations.noActiveShares': 'No active shares',
  },
  bn: {
    'language.label': 'ভাষা',
    'language.english': 'English',
    'language.bangla': 'বাংলা',
    'language.switchToBangla': 'বাংলা',
    'language.switchToEnglish': 'English',
    'nav.home': 'হোম',
    'nav.offers': 'অফার',
    'nav.products': 'পণ্য',
    'nav.cart': 'কার্ট',
    'nav.orders': 'অর্ডার',
    'nav.addresses': 'ঠিকানা',
    'nav.admin': 'অ্যাডমিন',
    'nav.signOut': 'সাইন আউট',
    'nav.profile': 'প্রোফাইল',
    'admin.panel': 'অ্যাডমিন প্যানেল',
    'admin.dashboard': 'ড্যাশবোর্ড',
    'admin.orders': 'অর্ডার',
    'admin.products': 'পণ্য',
    'admin.offers': 'অফার',
    'admin.locations': 'লাইভ লোকেশন',
    'admin.role': 'অ্যাডমিন',
    'admin.backToStore': 'স্টোরে ফিরে যান',
    'admin.store': 'স্টোর',
    'loading': 'লোড হচ্ছে...',
    'home.specialOffers': 'বিশেষ অফার',
    'home.shopByCategory': 'ক্যাটাগরি অনুযায়ী কিনুন',
    'home.lpgCylinders': 'এলপিজি সিলিন্ডার',
    'home.bestSellers': 'বেস্ট সেলার',
    'home.services': 'সার্ভিসসমূহ',
    'home.bookNow': 'এখন বুক করুন',
    'home.setDeliveryLocation': 'ডেলিভারি লোকেশন সেট করুন',
    'home.shareLocationText': 'দ্রুত ডেলিভারির জন্য আপনার লোকেশন শেয়ার করুন',
    'products.title': 'পণ্য ও সার্ভিস',
    'products.subtitle': 'এলপিজি সিলিন্ডার, চুলা, বার্নার, এক্সেসরিজ ও সার্ভিস খুঁজুন',
    'products.searchPlaceholder': 'পণ্য, কোম্পানি, সাইজ, ভালভ বা সার্ভিস খুঁজুন...',
    'products.all': 'সব',
    'products.lpgCylinders': 'এলপিজি সিলিন্ডার',
    'products.stovesBurners': 'চুলা ও বার্নার',
    'products.accessories': 'এক্সেসরিজ',
    'products.services': 'সার্ভিস',
    'products.noProducts': 'কোনো পণ্য পাওয়া যায়নি',
    'products.viewDetails': 'বিস্তারিত দেখুন',
    'cart.empty': 'আপনার কার্ট খালি',
    'cart.emptySubtitle': 'শুরু করতে সিলিন্ডার ও পণ্য যোগ করুন',
    'cart.title': 'শপিং কার্ট',
    'cart.promoCode': 'প্রোমো কোড',
    'cart.orderSummary': 'অর্ডার সারাংশ',
    'cart.subtotal': 'সাবটোটাল',
    'cart.estimatedTotal': 'সম্ভাব্য মোট',
    'checkout.orderPlaced': 'অর্ডার হয়েছে!',
    'checkout.confirmed': 'আপনার অর্ডার নিশ্চিত হয়েছে এবং শীঘ্রই ডেলিভারি করা হবে।',
    'checkout.title': 'চেকআউট',
    'checkout.deliveryAddress': 'ডেলিভারি ঠিকানা',
    'checkout.noSavedAddresses': 'কোনো সংরক্ষিত ঠিকানা নেই',
    'checkout.deliveryFloor': 'ডেলিভারি ফ্লোর',
    'checkout.free': 'ফ্রি',
    'orders.title': 'আমার অর্ডার',
    'orders.noOrders': 'কোনো অর্ডার পাওয়া যায়নি',
    'orders.shareLocation': 'লোকেশন শেয়ার করুন',
    'orders.sharingLocation': 'লাইভ লোকেশন শেয়ার হচ্ছে',
    'orders.locationHelp': 'দ্রুত ডেলিভারির জন্য আমাদের আপনাকে খুঁজে পেতে সাহায্য করুন',
    'orders.locationLive': 'ডেলিভারি টিম রিয়েল-টাইমে আপনাকে দেখতে পারবে',
    'addresses.title': 'ডেলিভারি ঠিকানা',
    'addresses.edit': 'ঠিকানা সম্পাদনা',
    'addresses.add': 'নতুন ঠিকানা যোগ করুন',
    'profile.title': 'প্রোফাইল সেটিংস',
    'profile.edit': 'প্রোফাইল সম্পাদনা',
    'profile.fullName': 'পূর্ণ নাম',
    'profile.email': 'ইমেইল',
    'profile.phone': 'ফোন নম্বর',
    'profile.save': 'পরিবর্তন সংরক্ষণ',
    'profile.changePassword': 'পাসওয়ার্ড পরিবর্তন',
    'profile.adminDashboard': 'অ্যাডমিন ড্যাশবোর্ড',
    'offers.title': 'বিশেষ অফার',
    'offers.active': 'চলমান অফার',
    'offers.promoCodes': 'প্রোমো কোড',
    'offers.none': 'এখন কোনো অফার নেই',
    'offers.checkBack': 'নতুন অফারের জন্য পরে আবার দেখুন!',
    'product.notFound': 'পণ্য পাওয়া যায়নি',
    'product.home': 'হোম',
    'product.products': 'পণ্য',
    'product.company': 'কোম্পানি',
    'product.size': 'সাইজ',
    'product.valveSize': 'ভালভ সাইজ',
    'product.valveType': 'ভালভ টাইপ',
    'product.notes': 'নোট (ঐচ্ছিক)',
    'product.quantity': 'পরিমাণ:',
    'product.delivery': 'বাংলাদেশজুড়ে ডেলিভারি',
    'type.new': 'নতুন',
    'type.refill': 'রিফিল',
    'type.service': 'সার্ভিস',
    'status.pending': 'পেন্ডিং',
    'status.confirmed': 'কনফার্মড',
    'status.processing': 'প্রসেসিং',
    'status.delivered': 'ডেলিভার্ড',
    'status.cancelled': 'ক্যানসেলড',
    'adminProducts.title': 'পণ্য',
    'adminProducts.add': 'পণ্য যোগ করুন',
    'adminProducts.search': 'পণ্য, কোম্পানি, সাইজ, ভালভ, সার্ভিস খুঁজুন...',
    'adminProducts.noProducts': 'কোনো পণ্য পাওয়া যায়নি',
    'adminOrders.title': 'অর্ডার',
    'adminOrders.allStatuses': 'সব স্ট্যাটাস',
    'adminOrders.noOrders': 'কোনো অর্ডার পাওয়া যায়নি',
    'adminLocations.title': 'লাইভ কাস্টমার লোকেশন',
    'adminLocations.mapError': 'গুগল ম্যাপ লোড হয়নি',
    'adminLocations.loadingMap': 'ম্যাপ লোড হচ্ছে...',
    'adminLocations.noCustomers': 'কোনো কাস্টমার লোকেশন শেয়ার করছেন না',
    'adminLocations.noActiveShares': 'কোনো অ্যাক্টিভ শেয়ার নেই',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    const saved = window.localStorage.getItem(STORAGE_KEY);
    return saved === 'bn' || saved === 'en' ? saved : 'en';
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === 'bn' ? 'bn' : 'en';
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    toggleLanguage: () => setLanguageState((current) => (current === 'en' ? 'bn' : 'en')),
    t: (key: string) => translations[language][key] || translations.en[key] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
